[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[functions.environment]
  STRIPE_SECRET_KEY = "${STRIPE_SECRET_KEY}"
  URL = "${URL}"
